name: myenv
channels:
  - conda-forge
  - peterschueller
  - potassco
dependencies:
  - python=3.7
  - fastapi
  - hexlite
  - SPARQLWrapper=1.8.5
  - Jinja2=2.11.3 
  - aiofiles=0.6.0
  - typing-extensions